#ifndef _PWRCTRL_APP_CONFIG_H_
#define _PWRCTRL_APP_CONFIG_H_


#include <driver/gpio.h>


#define APP_CONFIG_SSR_PINS {GPIO_NUM_20, GPIO_NUM_21, GPIO_NUM_22}
#define APP_CONFIG_UART_RX GPIO_NUM_16
#define APP_CONFIG_UART_NUM UART_NUM_1


#endif
