name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0.1
        target: esp32

    - name: Prepare firmware
      run: |
        cp build/pwrctrl.bin firmware.bin
        git describe --tags --always --dirty > firmware.version

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: firmware.*
