name: Deploy

on:
  push:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0.1
        target: esp32
    - name: Prepare firmware
      run: cp build/pwrctrl.bin firmware.bin
    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        add: 'firmware.bin'
        message: 'Update firmware.bin'
        default_author: github_actions
